### ISSUE TITLE
No logro pasar del login password

### ISSUE THREAD

**Issue by Santiagoc57** [OscarDogar/Platzi-Download#100]
Buenas tardes Oscar de ante mano agradecerte por maravilloso proyecto, lo he utilziando en diversas ocaciones, pero en esta me encuentro que al ejecutar el .exe, se carga el correo, pero no la contraseña, es extraño porque lo intente una vez y funciono, pero las siguientes se queda cargada la interfaz de contraseña.

Sabes cual puede ser el problema? Gracias

**Comment by OscarDogar** [comment]
No se que pueda ser, tal vez sea el chromer driver o la conexion a internet, porque yo estuve probando con el código y el .exe y con los 2 funciona
