### ISSUE TITLE
Por que se borra la carpeta videos vuando se ha terminado la descarga?

### ISSUE THREAD

**Issue by dudufcb4** [OscarDogar/Platzi-Download#101]
![image](https://github.com/user-attachments/assets/33667f04-4502-416f-9e93-0b8cf2812c18)
Solo me crea esas carpetas estoy usando el compilado.

**Comment by OscarDogar** [comment]
La carpeta videoInfo se usa para descargar los segmentos y cuando se descarguen todos se usa ffmpeg(importante tener instalado) para volverlos un solo video y una vez se crea el video(el cual debería quedar a fuera de la carpeta videoInfo) se procede a eliminar la carpeta videoInfo.
