### ISSUE TITLE
Bug se queda pegado en el examen

### ISSUE THREAD

**Issue by eliottp1089** [OscarDogar/Platzi-Download#52]
En la nueva versión al momento de estar buscando los videos, pasa al examen y se queda pegado allí y sale del programa.

**Comment by OscarDogar** [comment]
El examen al que te refieres es el examen final de certificado o los quizes entre videos?

**Comment by eliottp1089** [comment]
> El examen al que te refieres es el examen final de certificado o los quizes entre videos?

Al certificado final pero no sucede en todos los cursos estoy viendo, sucede creo que cuando el certificado entra como una clase 

Ejemplo: https://platzi.com/cursos/serverless-avanzado/ este curso

**Comment by DARKSHADOW00285** [comment]
hola, a que se debe este error 
![Screenshot_3](https://github.com/OscarDogar/Platzi-Download/assets/64561221/feee4b6e-569d-4d4b-a408-45be52a716b4)
