### ISSUE TITLE
Soporte para aria2

### ISSUE THREAD

**Issue by eliottp1089** [OscarDogar/Platzi-Download#54]
Se podría incluir en el proceso de descarga que baje con un downloader externo que se llama aria2. Este tiende a bajar mucho más rápido los chunks del stream. Solo si es posible y está dentro de sus posibilidades. Si cree que se complique cierre la issue.

**Comment by OscarDogar** [comment]
Si quisiera agregar aria2, pero no creo que pueda en este momento.
