### ISSUE TITLE
problema al buscar los videos

### ISSUE THREAD

**Issue by DARKSHADOW00285** [OscarDogar/Platzi-Download#58]
![Screenshot_3](https://github.com/OscarDogar/Platzi-Download/assets/64561221/3fee45d9-d0b5-4652-86f6-3bfaebd02caa)

**Comment by ak47flow** [comment]
Me sale igual, pero parece que es porque no encuentra nada en los recursos, verifique en la clase y cuando no hay recursos me sale este error.
![Captura de pantalla 2023-12-27 204409](https://github.com/OscarDogar/Platzi-Download/assets/92182994/aaeb4396-68d4-4929-9869-8c04bf9e69e5)

**Comment by OscarDogar** [comment]
> Me sale igual, pero parece que es porque no encuentra nada en los recursos, verifique en la clase y cuando no hay recursos me sale este error. ![Captura de pantalla 2023-12-27 204409](https://private-user-images.githubusercontent.com/92182994/293120841-aaeb4396-68d4-4929-9869-8c04bf9e69e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzOTQwNTAsIm5iZiI6MTcwNDM5Mzc1MCwicGF0aCI6Ii85MjE4Mjk5NC8yOTMxMjA4NDEtYWFlYjQzOTYtNjhkNC00OTI5LTk4NjktOGMwNGJmOWU2OWU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA0VDE4NDIzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5ODNkYmM0NjFjZTE4YTBlODJiMTU5ZjczNzYzMzI4OTA3NDE5MjJmODZjZmIwOWYzMjhiN2EwZTdlODUxYTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.p-8mqYRLLOafmK6BQuSog_4KTXD0Q61saLOwtDk877Y)

Si, el problema era porque no estaba encontrando el tab de recursos, ya hice la validacion para que no falle en estos casos
