### ISSUE TITLE
nuevo error

### ISSUE THREAD

**Issue by DARKSHADOW00285** [OscarDogar/Platzi-Download#67]
hola oscar espero estes bien, ha aparecido este error, y la pagina de login de  platzi ha cambiado
![Screenshot_2](https://github.com/OscarDogar/Platzi-Download/assets/64561221/1491725b-0859-470b-94df-7109d3bcf99c)

![Screenshot_3](https://github.com/OscarDogar/Platzi-Download/assets/64561221/cce9ca2b-ee60-43f1-b762-c2bb2899e9e3)

**Comment by OscarDogar** [comment]
Ya quedaton los cambios para el nuevo login
