### ISSUE TITLE
nuevo error

### ISSUE THREAD

**Issue by DARKSHADOW00285** [OscarDogar/Platzi-Download#76]
hola oscar buenas noches, espero estes  bien y gracias por tu trabajo, me ha aparecido este nuevo error : 
![image](https://github.com/OscarDogar/Platzi-Download/assets/64561221/f71a609f-84b7-4623-bbcd-c3cb7d588c04)
 podria tener solucion,gracias

**Comment by OscarDogar** [comment]
@DARKSHADOW00285 Como tal no son errores en sí, sino más bien warnings. Veo que el curso que están intentando descargar es este https://platzi.com/cursos/intro-softr/ el cual tiene 17 videos.

> [!WARNING]
> 1. All retries failed, este error aparece cuando después de varios intentos no logra encontrar la parte que falta, esto puede ser por varios factores siendo el principal por problemas de internet o conexión lenta. 
>2. Veo que llego hasta la clase 14, hay veces que por problemas de internet no alcanza a obtener ciertos elementos y lo que hace es saltarlos u omitirlos.

> [!TIP]
>Lo mejor sería volver a correr el programa, pero desde el link de la clase 14.

**Comment by DARKSHADOW00285** [comment]
![Screenshot_1](https://github.com/OscarDogar/Platzi-Download/assets/64561221/68e55184-e4b2-42dc-b0d6-760fbf5070ee

tengo buena conexion (500mb) y pues volvi a descargar pero el error aparece

**Comment by OscarDogar** [comment]
Intenta correrlo con pocas ventanas abiertas. 
Estaba descargando ese curso pero me lo descargo normalmente sin ningun error.


Started downloading 2. Conoce el proyecto del curso aplicación de reserva de restaurantes
[██████████████████████████████████████████████████] 24/24 100.00%
Started downloading 3. Introducción al app builder
[██████████████████████████████████████████████████] 85/85 100.00%
Started downloading 4. Dónde están mis datos Estructura de la base de datos
[██████████████████████████████████████████████████] 70/70 100.00%
Started downloading 5. Los 4 tipos de pantallas
[██████████████████████████████████████████████████] 88/88 100.00%
Started downloading 6. Componentes cómo funcionan
[██████████████████████████████████████████████████] 79/79 100.00%
Started downloading 7. Formas crearlas y editarlas
[██████████████████████████████████████████████████] 58/58 100.00%
Started downloading 8. Cómo agrupar filtrar y ordenar la información
[██████████████████████████████████████████████████] 56/56 100.00%
Started downloading 9. Cómo funcionan las tabs
[██████████████████████████████████████████████████] 60/60 100.00%
Started downloading 10. Cómo editar y eliminar datos
[██████████████████████████████████████████████████] 72/72 100.00%
Started downloading 11. Pagos cómo usar Stripe
[██████████████████████████████████████████████████] 100/100 100.00%
Started downloading 12. Cómo funciona el componente de elección
[██████████████████████████████████████████████████] 95/95 100.00%
Started downloading 13. Definiendo diferentes tipos de usuarios
[██████████████████████████████████████████████████] 84/84 100.00%
Started downloading 14. Configuración de condiciones de visibilidad en componentes
[██████████████████████████████████████████████████] 54/54 100.00%
Started downloading 15. Filtrar la información en las pantallas de listas
[██████████████████████████████████████████████████] 66/66 100.00%
Started downloading 16. Cómo funcionan las relaciones
[██████████████████████████████████████████████████] 65/65 100.00%
Started downloading 17. Cómo agregar una lista de datos dentro de una vista de detalle
[██████████████████████████████████████████████████] 36/36 100.00%
Started downloading 18. Cómo funciona la columna de lookup
[██████████████████████████████████████████████████] 61/61 100.00%
Started downloading 19. Aprobar o rechazar usuarios
[██████████████████████████████████████████████████] 42/42 100.00%
Started downloading 20. Cómo pagar y descargar productos digitales
[██████████████████████████████████████████████████] 74/74 100.00%
--------Finished--------
