### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by arlessweschler** [OscarDogar/Platzi-Download#78]
Check details here. 

**Please enter the URL of the class you want to download: https://platzi.com/clases/4294-excel-avanzado-macros/54815-que-es-vba-y-que-son-las-macros/

Do you want to download only this video or this and the following videos?

1. Just this one
2. This one and the following
Type: 1
Finding videos...
Message: element click intercepted: Element is not clickable at point (161, 744)
  (Session info: chrome=123.0.6312.86)
Stacktrace:
        GetHandleVerifier [0x00DF4CC3+225091]
        (No symbol) [0x00D24E11]
        (No symbol) [0x00BC9A7A]
        (No symbol) [0x00C06D42]
        (No symbol) [0x00C05574]
        (No symbol) [0x00C035DB]
        (No symbol) [0x00C027BA]
        (No symbol) [0x00BF98DE]
        (No symbol) [0x00C1F55C]
        (No symbol) [0x00BF930E]
        (No symbol) [0x00C1F7F4]
        (No symbol) [0x00C35CB0]
        (No symbol) [0x00C1F2F6]
        (No symbol) [0x00BF79B9]
        (No symbol) [0x00BF879D]
        sqlite3_dbdata_init [0x01269A63+4064547]
        sqlite3_dbdata_init [0x0127106A+4094762]
        sqlite3_dbdata_init [0x0126B968+4072488]
        sqlite3_dbdata_init [0x00F6C9C9+930953]
        (No symbol) [0x00D307E4]
        (No symbol) [0x00D2AD08]
        (No symbol) [0x00D2AE31]
        (No symbol) [0x00D1CAA0]
        BaseThreadInitThunk [0x76637BA9+25]
        RtlInitializeExceptionChain [0x7764BDAB+107]
        RtlClearBits [0x7764BD2F+191]

Press enter to exit
Exception ignored in: <function Chrome.__del__ at 0x000001613B6CB740>
Traceback (most recent call last):
  File "undetected_chromedriver\__init__.py", line 843, in __del__
  File "undetected_chromedriver\__init__.py", line 798, in quit
OSError: [WinError 6] Controlador no válido

**Comment by watercubz** [comment]
Hi, @arlessweschler, to resolve the error mentioned above, we hope you have previously installed ffmpeg and Chromedriver, and let's see what is installed with the next command, winget install "FFmpeg (Essentials Build)", after this, create an account Google, and link it to platzi through https://platzi.com/signup/ and register email, there you put the newly created Google account, and link it, then later in your .env file add the new account already registered in platzi and after that restart the pc run the program and that would be it. Att: watercubz ❤️
