### ISSUE TITLE
Ejecuta todo perfectamente pero no convierte la Playlist a mp4/falla dependencia.cffi==1.15.1 

### ISSUE THREAD

**Issue by johnunleashed** [OscarDogar/Platzi-Download#79]
Estimado Óscar gracias por el aporte demasiado genial hice todas las pruebas correspondientes y resulta que al instalar el archivo requerimientos.txt se me presenta un error con una de las dependencias la cual copió abajo es la única dependencia que presenta error, las demás dependencias se instalan correctamente:
la falla dice asi: 

Collecting cffi==1.15.1 (from -r requirements.txt (line 5))
  Using cached cffi-1.15.1.tar.gz (508 kB)
  Installing build dependencies ... done
  **Getting requirements to build wheel ... error
  error: subprocess-exited-with-error**

[falla dependencia.txt](https://github.com/OscarDogar/Platzi-Download/files/14812846/falla.dependencia.txt)

revise y todas las dependencias y todas estan ok. 
Corro el programa y funciona perfecto, hasta descarga 1 a 1 los trozos de los videos del archivo M3U8, hasta alli bien. 
![image](https://github.com/OscarDogar/Platzi-Download/assets/105758484/50b96b93-d504-49bb-8f55-ea67fbb47961)

Pero luego de descargar todos los trozos..no genera el mp4. sino que queda la playlist en M3u8..:( 

![image](https://github.com/OscarDogar/Platzi-Download/assets/105758484/970f7c74-2ced-4030-a2cd-c31c38e35034)

Donde podra estar la falla.. Ah por cierto el sistema al revisar el sistema instala por defecto el cffi==1.16.0 de manera correcta pero no es la version que dice requerimientos.txt.

**Comment by OscarDogar** [comment]
Intenta de nuevo, porque hace rato que no actualizaba requirements.txt o tal vez sea porque no tienes instalado ffmpeg, y tambien si lo deseas puedes intentar probar con el  [ejecutable](https://github.com/OscarDogar/Platzi-Download/releases)
