### ISSUE TITLE
No descarga los trozos de videos y no convierte MP4 creo que tiene que ver con el fix: 🐛 Update user agent and handle additional download elements #83, mi user agente es la version 123 de chrome

### ISSUE THREAD

**Issue by johnunleashed** [OscarDogar/Platzi-Download#89]
Estimado Oscar, le comento, el archivo se ejecuta perfectamente pero a la hora de find videos , crea la carperta Info videos pero no logra encontrar los trozos de videos para unirlos, borra la carpeta y no se genera el mp4. tengo instaldo el ffmpeg con su path en el equipo. adjunto el comportamiento en:
no funciona ni en  modo 1 ni en modo 2 mismo comportamineto
![image](https://github.com/OscarDogar/Platzi-Download/assets/105758484/439a40ed-df90-4363-8852-40f2da5e777b)

al final 
![image](https://github.com/OscarDogar/Platzi-Download/assets/105758484/ed2f8b81-e8cc-4d6e-969c-13082c22de90)

La barra dice que esta encontrando los videos pero al final crea la carpeta pero no descarga los trozos de video para unirlos.

**Comment by johnunleashed** [comment]
Hola oscar, como estas.. pudo revisar el issue?? Muchas Gracias..

**Comment by OscarDogar** [comment]
> Hola oscar, como estas.. pudo revisar el issue?? Muchas Gracias..

Si, el problema parece ser que si era el user_agent
