### ISSUE TITLE
No encuentra la URL

### ISSUE THREAD

**Issue by Samuh-El** [OscarDogar/Platzi-Download#92]
intenté usar la app con esta url [https://platzi.com/new-home/clases/5356-mongodb-modelado/58034-ya-tomaste-el-curso-de-introduccion-de-mongodb/] y me sale error:

`_Please enter the URL of the class you want to download: https://platzi.com/new-home/clases/5356-mongodb-modelado/58034-ya-tomaste-el-curso-de-introduccion-de-mongodb/

Do you want to download only this video or this and the following videos?

1. Just this one
2. This one and the following
Type: 2
HTTP Error 404: Not Found
Press enter to exit_`

**Comment by OscarDogar** [comment]
Intentan cambiar el chromedriver o tal vez fue un problema de conexion. porque cuando hice la prueba si descargo.

Please enter the URL of the class you want to download: https://platzi.com/new-home/clases/5356-mongodb-modelado/58034-ya-tomaste-el-curso-de-introduccion-de-mongodb/

Do you want to download only this video or this and the following videos?

1. Just this one
2. This one and the following
Type: 1
Finding videos...
Started downloading 1. Ya tomaste el Curso de Introducción de MongoDB1  22
[██████████████████████████████████████████████████] 36/36 100.00%
--------Finished--------

**Comment by Samuh-El** [comment]
seria mucho pedir si le dejas la URL del chromedriver qie estas usando? porfavor? para salir de dudas si es eso..

**Comment by OscarDogar** [comment]
> seria mucho pedir si le dejas la URL del chromedriver qie estas usando? porfavor? para salir de dudas si es eso..

Desde aqui se puede descargar https://developer.chrome.com/docs/chromedriver/downloads dependiendo de la versión de chrome que tengas actualmente tocaría descargar la versión del chromedriver correspondiente.
