### ISSUE TITLE
There was an error finding the elements

### ISSUE THREAD

**Issue by carfer99** [OscarDogar/Platzi-Download#93]
Hola Oscar 👋 espero estés muy bien,
Quisiera reportar un error al hacer uso del ejecutable, tal vez por el cambio de ubicación de las clases en la nueva interfaz, muestra el error "There was an error finding the elements".

![Captura de pantalla 2024-05-30 213423](https://github.com/OscarDogar/Platzi-Download/assets/80804718/c35af0dd-88e9-4546-ace0-b0d5df385e6f)

![Captura de pantalla 2024-05-30 213524](https://github.com/OscarDogar/Platzi-Download/assets/80804718/8c592e92-58e4-45c4-8e6f-9f81ea8ecc40)

Agradezco mucho tus aportes, si requieres acceso a la plataforma estaré al pendiente aunque ya no me quedan muchos días de suscripción.

**Comment by OscarDogar** [comment]
Si fue por el cambio de interfaz, ya cambie algunos selectores.
