### ISSUE TITLE
pregunta

### ISSUE THREAD

**Issue by DARKSHADOW00285** [OscarDogar/Platzi-Download#97]
hola oscar, disculpa las molestias, queria preguntarte si conoces alguna forma de que el software no sea reconocido por platzi, ya que platzi ahora detecta actividad inusual y me bloquearon una cuenta, nose si sepas algo al respecto

**Comment by OscarDogar** [comment]
Es difícil saber cómo detectan la actividad si mediante ip, si mediante request… Yo me inclinaría más por el número de horas medidas en la página de [progreso](https://platzi.com/estadisticas/) y los puntos, es decir, si antes venias haciendo solo 2 cursos y cierta cantidad de puntos por semana, y luego se pasa a muchos mas cursos y puntos si se podría ver un poco inusual, yo recomendaría no descargar muchos cursos a la vez.
